### PR TITLE
Stack

### PR DESCRIPTION
**Pull request by damianday**
Tried to keep the implementation as close to Queue/List as possible.
I've included tests to ensure everything works as expected - which are commented out.

### CODE REVIEW

**Comment by bfiete** [comment]
Just wondering - what is the use case for an explicit stack vs a List? It just removes random-access functionality, but a list already has Add, PopBack, and the Back property...

**Comment by damianday** [comment]
Yeah I've seen a few stack implementations which just wrap a an array list. The only gain I can think of is familiarity, especially with people coming from c# and a cleaner API.

**Comment by JamesOrson** [comment]
I think the benefit of a Stack here would depend on the implementation of the List people generally use as a Stack.

A Stack can be made to be incredibly efficient using a LinkedList. Insertion and deletion are still O(1) operations that way. Depending on the implementation of the List, the List may have more memory allocated than necessary for the size of the Stack.

So say the List has allocated 8 spots for items and all of them are filled up. If I go to add an item to the "Stack", in a normal implementation of an expandable collection, the List's capacity would be doubled to 16 spots leaving the List with 7 empty spots that may never be used.

A Stack implemented with a LinkedList would only consume as much memory as is being used at any given time. Unless the Stack is still slab allocated the same way as the List, with nodes on standby.

**Comment by JamesOrson** [comment]
> I think the benefit of a Stack here would depend on the implementation of the List people generally use as a Stack.
> 
> A Stack can be made to be incredibly efficient using a LinkedList. Insertion and deletion are still O(1) operations that way. Depending on the implementation of the List, the List may have more memory allocated than necessary for the size of the Stack.
> 
> So say the List has allocated 8 spots for items and all of them are filled up. If I go to add an item to the "Stack", in a normal implementation of an expandable collection, the List's capacity would be doubled to 16 spots leaving the List with 7 empty spots that may never be used.
> 
> A Stack implemented with a LinkedList would only consume as much memory as is being used at any given time. Unless the Stack is still slab allocated the same way as the List, with nodes on standby.

I see that this implementation still follows the methodology of "When I am full, double my capacity", so there really is not a difference in this implementation from just using a List with `Add`, `PopBack`, and `Back`.

**Comment by damianday** [comment]
I'll close the pull for now, because their is not much benefit over the list implementation.

**Pull request closed without merging**
