### PR TITLE
Base64 text encoding 3(Updated)

### PR DESCRIPTION
**Pull request by Argentoz**
Added Base64 text encoding
Example code:
```
	String InText = "SGVsbG8sIHdvcmxkIQ==";
	String OutText = scope String;
	Base64.DecodeString(InText, OutText);
	Console.WriteLine(OutText);
```
`Output: Hello, world!`

### CODE REVIEW

**Comment by bfiete** [comment]
That does bring up a good question - "what is the best output type for generic binary output"? I think List<uint8> is better than a String, for sure. But maybe an ISequentialStream interface is really the right kind of thing...

**Comment by bfiete** [comment]
But anyway- what I would have done here is had a DecodeData decode to a Span - because the output size can be trivially determined ahead of time.

Then have a DecodeString that reserves the correct amount of space in the string and then passes in the correct Span (rather than allocating once for List and once for String as you do now). Then also have a List<uint8> that also reserves the correct amount of space and then calls the DecodeData with the Span

**Comment by Argentoz** [comment]
1

**Comment by Argentoz** [comment]
close

**Pull request closed without merging**
