### PR TITLE
Add String.Insert char32

### PR DESCRIPTION
**Pull request by damianday**
Use CalcNewSize in Insert.
Remove a duplicated Insert char8 by using default parameter.
Add new Insert method accepting char32.

### CODE REVIEW

**Comment by damianday** [comment]
Good spot copy and paste failed me :/ I'll make some changes and test properly.

**Comment by damianday** [comment]
@bfiete Should Append and Insert use UTF8.Encode? I can see its avoided I assume to avoid the overhead?

**Comment by bfiete** [comment]
These char-appending methods are considered high priority for optimization, as they may be used to build large strings one character at a time. But- of course, for optimization the rule should be 'measure, don't assume'.

I timed some different implementations in Debug and Release. I found an even better implementation for Append. With a 2-byte UTF8 char, it's about 50% faster than versions that separately call GetEncodedLength in Release mode, with both the previous versions and a UTF8.Encode version being about the same speed as each other. In Debug, the previous version is about 20% faster than calling UTF8.Encode, but the new version at https://github.com/beefytech/Beef/commit/b5815927efd0e926a214dc5e2ecc4e686b16a491 is almost twice as fast.

And I do like having the separate versions of Append and Insert without the count parameter- it's by far the common case and it takes that extra beat of brainpower to wonder why there's that extra parameter you're not expecting in autocomplete, and there is a slight speed advantage when the method doesn't get inlined (ie: Debug mode).

**Comment by bfiete** [comment]
Looks good.

**Pull request merged**
