### PR TITLE
Add Ctrl+C handler to Console.bf

### PR DESCRIPTION
**Pull request by thibmo**
I did notice that BfCallAllStaticDtors is called before this event is handled, not too sure where/how to resolve that issue.

### CODE REVIEW

**Comment by thibmo** [comment]
Coming back on that note, seems like it's doing things properly, fault was on my end. :)

**Comment by bfiete** [comment]
I submitted a different version of this at https://github.com/beefytech/Beef/commit/c3e6282a8bd661df413dfe1a2428de881a05ebe3

I don't really like how Microsoft exposed this functionality- this `Object target, Args args` pattern they tend to use is not a good fit here, I don't think.

Also- please try to adhere to corlib coding conventions for corlib submissions-
ie:
```C#
public static void RemoveCancelKeyPressCallback(ConsoleCancelEventHandler handler)
{
	mCancelKeyPress.Remove(handler);
	if ((mCancelKeyPress.Count == 0) && (WindowsConsole.CtrlHandlerAdded))
		WindowsConsole.RemoveCtrlHandler();
}
```
rather than
```C#
public static void RemoveCancelKeyPressCallback(ConsoleCancelEventHandler handler)
{
	_cancelKeyPress.Remove(handler);
	if (_cancelKeyPress.Count == 0 && WindowsConsole.CtrlHandlerAdded)
		WindowsConsole.RemoveCtrlHandler();
}
```

**Comment by thibmo** [comment]
Fair points, I'll fix the CC violations asap.
As for signal handling, what would be preferred over this direct port? A more C-like signal()?

**Comment by bfiete** [comment]
Hm? I already added this functionality here: https://github.com/beefytech/Beef/commit/c3e6282a8bd661df413dfe1a2428de881a05ebe3

**Comment by thibmo** [comment]
Ah sorry, looked over that bit of the previous comment. Fair enough, can close this PR then. :)

**Pull request closed without merging**
