### PR TITLE
Update llvm_build.bat

### PR DESCRIPTION
**Pull request by apg360**
Hi,

.bat to be like .sh
Not implemented the "llvm-11.0.0.src.tar.xz" because there is no default tar file support in windows, should we use unrar or 7zip ? .... that is a question of another day.

Kind regards

### CODE REVIEW

**Comment by apg360** [comment]
@bfiete, good morning, please have a look at this pull request.
Awaiting your feedback please.

**Comment by bfiete** [comment]
Why did you remove `--config core.autocrlf=false`?

It is recommended here for Windows: https://llvm.org/docs/GettingStarted.html#getting-the-source-code-and-building-llvm

**Comment by bfiete** [comment]
As for 7-zip - we could just require the user to extract the source archive themselves beforehand.

**Comment by apg360** [comment]
> Why did you remove `--config core.autocrlf=false`?
> 
> It is recommended here for Windows: https://llvm.org/docs/GettingStarted.html#getting-the-source-code-and-building-llvm

@bfiete 

Very sorry, my mistake.

I just added it back now .... would you please have a look again.

Kind regards

**Comment by bfiete** [comment]
Thanks

**Pull request merged**
