### PR TITLE
Added generic EnumToString method

### PR DESCRIPTION
**Pull request by M0n7y5**

### CODE REVIEW

**Comment by bfiete** [comment]
Why not just use the `ToString` method?

**Comment by M0n7y5** [comment]
@bfiete What do you mean?

**Comment by bfiete** [comment]
`val.ToString(str)` works for every type. In the case of an enum, it outputs the name of the enum value.

**Comment by bfiete** [comment]
Yes

**Comment by M0n7y5** [comment]
It works ... nice 👍

**Comment by M0n7y5** [comment]
Is this behavior in described docs?

**Comment by bfiete** [comment]
No- mostly the docs only cover language features

**Comment by M0n7y5** [comment]
I think it needs to be mentioned in docs or at least mention some similarities with C# so people can get the idea how Beef Enum works by looking at C# Enum docs. At least add some oneliner that will mention it in docs.

**Comment by M0n7y5** [comment]
Should i close this issue?

**Pull request closed without merging**
