### PR TITLE
Array CopyTo for spans

### PR DESCRIPTION
**Pull request by damianday**
CopyTo, allows copying memory from an array to a span.

### CODE REVIEW

**Comment by bfiete** [comment]
I don't think there should be a `length` on the second one. It's trivial to create a new span with a shorter length if you don't want to fill out the whole span...

**Comment by damianday** [comment]
Thats true, I've removed the length parameter.

**Comment by bfiete** [comment]
Just one more thing- the length check doesn't take into account the offset.
`Debug.Assert(destination.Length >= mLength);`
should be
`Debug.Assert((uint)srcOffset + (uint)destination.[Friend]mLength <= (uint)mLength);`
The `[Friend]mLength` part is sortof optional because it's an `[Inline]` anyway, but it's still slightly faster in debug mode (especially on the LLVM backend).

**Comment by bfiete** [comment]
Oh, actually you set this up the inverse of what I expected- the length copied should be the size of the span, not the size of the array.

**Pull request merged**
